In [ ]:
Part 1: Theoretical Questionk
1. What are the different data structures used in Tensorflow?. Give some examplesc
2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an examplec
3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

## Part 1

In [ ]:
1. Tensors are the basic data structures in TensorFlow, and they represent the connecting edges in a dataflow graph.

A tensor simply identifies a multidimensional array or list. The tensor structure can be identified with three parameters: rank, shape, and type.

a. Rank: Identifies the number of dimensions of the tensor. A rank is known as the order or n-dimensions of a tensor, where for example rank 1 tensor is a vector or rank 2 tensor is matrix.

b. Shape: The shape of a tensor is the number of rows and columns it has.
    
c. Type: The data type assigned to tensor elements

2. constant vs variable

In [1]:
import tensorflow as tf

In [4]:
a=tf.constant(42)
a

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [13]:
a.assign(98)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [6]:
b=tf.Variable(42)
b

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>

In [12]:
b.assign(98)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=98>

## In TensorFlow the differences between constants and variables are that when you declare some constant, its value can't be changed in the future (also the initialization should be with a value, not with operation).

## Nevertheless, when you declare a Variable, you can change its value in the future with tf.assign() method (and the initialization can be achieved with a value or operation).

3.matrix addition, multiplication, and element-wise operations in TensorFlow

In [14]:
mat_u=tf.constant([[1,2,3]])
mat_v=tf.constant([[1,2,3]])
mat_u

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [15]:
mat_v

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [17]:
mat_v_t=tf.transpose(mat_v)
mat_v_t

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]])>

In [18]:
tf.matmul(mat_u,mat_v_t)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]])>

In [19]:
mta=tf.add(mat_u,mat_v)
mta

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[2, 4, 6]])>

In [20]:
tf.multiply(mat_u,9)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[ 9, 18, 27]])>

In [ ]:
Part 2: Practical Implementation

Task 1: Creating and Manipulating Matricek
1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the 
values of matrix A
2. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display 
the values of matrix Bc
3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a 
mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values 
of matrix C
4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D
5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.
Task 2: Performing Additional Matrix Operationk
1. Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random_uniform 
functionc
2. Calculate the transpose of matrix F and store the result in matrix Gc
3. Calculate the element-wise exponential of matrix F and store the result in matrix Hc
4. Create a matrix I by concatenating matrix F and matrix G horizontallyc
5. Create a matrix J by concatenating matrix F and matrix H vertically.

## Part 2

### Task 1

In [27]:
Matrix_A=tf.random.normal(shape=(3,3),mean=0,stddev=1)
Matrix_A

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.849604  ,  0.63646567,  0.60850096],
       [ 1.594156  ,  0.23293778, -1.3201696 ],
       [ 0.38186222, -1.0438532 ,  0.13532962]], dtype=float32)>

In [28]:
Matrix_B=tf.random.truncated_normal(shape=(4,4),mean=0,stddev=1)
Matrix_B

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.40800196,  1.1491874 , -1.0792257 , -0.29867393],
       [ 0.99870497, -0.30080998,  1.0827218 , -0.9864211 ],
       [-0.7078753 ,  0.43343493, -0.01092538, -1.2660323 ],
       [-0.49040642, -0.1846441 , -0.3082931 , -0.70754355]],
      dtype=float32)>

In [29]:
Matrix_C=tf.random.normal(shape=(2,2),mean=3,stddev=0.5)
Matrix_C

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.7403977, 3.4328141],
       [3.1489785, 2.4894168]], dtype=float32)>

In [31]:
Matrix_A=tf.random.normal(shape=(4,4),mean=0,stddev=1)
Matrix_A

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-1.2771266 ,  1.8682204 , -1.0040886 , -0.03049994],
       [-0.24057871,  0.49932864, -0.9828422 ,  0.01500144],
       [ 0.5261143 , -0.4710401 , -0.4487373 , -0.08141351],
       [-0.0958588 , -0.0544923 ,  0.34899315,  0.3023947 ]],
      dtype=float32)>

In [32]:
Matrix_D=tf.add(Matrix_A,Matrix_B)

In [26]:
Matrix_D

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.78071547,  1.5762992 ,  1.4596301 ,  1.1229947 ],
       [ 2.5954452 , -1.2489655 , -0.68366015,  0.37744308],
       [-0.1847879 ,  1.1729108 , -0.5820359 ,  1.9351172 ],
       [ 0.22298789, -0.7818427 ,  1.4367635 , -0.3525564 ]],
      dtype=float32)>

In [33]:
Matrix_E=tf.matmul(Matrix_A,Matrix_D)
Matrix_E

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 3.7688546 , -3.4376826 ,  3.3075542 , -0.02911735],
       [ 0.95380783, -0.59342545,  1.0034603 ,  0.91238344],
       [-1.1143851 ,  1.5303348 , -0.94015455,  0.9220283 ],
       [-0.12049449, -0.38550037,  0.0461497 , -0.50827515]],
      dtype=float32)>

### Task 2

In [66]:
Matrix_F=tf.random.uniform(shape=(3,3),minval=0,maxval=10,dtype=tf.float32)
Matrix_F

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[8.970984 , 5.357276 , 3.057872 ],
       [1.7223895, 2.4699855, 4.9468684],
       [2.798183 , 2.134211 , 5.053072 ]], dtype=float32)>

In [67]:
Matrix_G=tf.transpose(Matrix_F)
Matrix_G

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[8.970984 , 1.7223895, 2.798183 ],
       [5.357276 , 2.4699855, 2.134211 ],
       [3.057872 , 4.9468684, 5.053072 ]], dtype=float32)>

In [68]:
a=tf.constant([1.,2.,3.])
a

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [69]:
Matrix_H=tf.math.exp(Matrix_G)
Matrix_H

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[7.8713467e+03, 5.5978885e+00, 1.6414793e+01],
       [2.1214626e+02, 1.1822275e+01, 8.4503775e+00],
       [2.1282221e+01, 1.4073355e+02, 1.5650250e+02]], dtype=float32)>

In [70]:
Matrix_I=tf.concat(values=[Matrix_F,Matrix_G],axis=1)
Matrix_I

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[8.970984 , 5.357276 , 3.057872 , 8.970984 , 1.7223895, 2.798183 ],
       [1.7223895, 2.4699855, 4.9468684, 5.357276 , 2.4699855, 2.134211 ],
       [2.798183 , 2.134211 , 5.053072 , 3.057872 , 4.9468684, 5.053072 ]],
      dtype=float32)>

In [71]:
Matrix_J=tf.concat(values=[Matrix_F,Matrix_G],axis=0)
Matrix_J

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[8.970984 , 5.357276 , 3.057872 ],
       [1.7223895, 2.4699855, 4.9468684],
       [2.798183 , 2.134211 , 5.053072 ],
       [8.970984 , 1.7223895, 2.798183 ],
       [5.357276 , 2.4699855, 2.134211 ],
       [3.057872 , 4.9468684, 5.053072 ]], dtype=float32)>